/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_globalpark_fastbit_FastbitPartition */

#ifndef _Included_com_globalpark_fastbit_FastbitPartition
#define _Included_com_globalpark_fastbit_FastbitPartition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_globalpark_fastbit_FastbitPartition
 * Method:    createCppObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitPartition_createCppObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitPartition
 * Method:    deleteCppObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitPartition_deleteCppObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
