/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_globalpark_fastbit_FastbitTablex */

#ifndef _Included_com_globalpark_fastbit_FastbitTablex
#define _Included_com_globalpark_fastbit_FastbitTablex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_globalpark_fastbit_FastbitTablex
 * Method:    createCppObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTablex_createCppObject
  (JNIEnv *, jobject);

/*
 * Class:     com_globalpark_fastbit_FastbitTablex
 * Method:    deleteCppObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTablex_deleteCppObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTablex
 * Method:    importCSV_native
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTablex_importCSV_1native
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitTablex
 * Method:    appendRow_native
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTablex_appendRow_1native
(JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
