/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_globalpark_fastbit_FastbitTable */

#ifndef _Included_com_globalpark_fastbit_FastbitTable
#define _Included_com_globalpark_fastbit_FastbitTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    createTable
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_createTable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    createCppObject
 * Signature: (Lcom/globalpark/fastbit/FastbitPartition;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_createCppObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    buildIndex_native
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_buildIndex_1native
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    buildIndexes_native
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_buildIndexes_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    select_native
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_select_1native
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    groupby_native
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_groupby_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    orderby_native
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_orderby_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    nrows_native
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_nrows_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    ncolumns_native
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_ncolumns_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    columnnames_native
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_globalpark_fastbit_FastbitTable_columnnames_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    columntypes_native
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_globalpark_fastbit_FastbitTable_columntypes_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    asString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_globalpark_fastbit_FastbitTable_asString_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    dump_native
 * Signature: (JLjava/io/Writer;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_dump_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    deleteCppObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_deleteCppObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    flushFromFileManager
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_flushFromFileManager
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    loadConf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitTable_loadConf
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeUNKNOWN
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeUNKNOWN
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeOID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeOID
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeBYTE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeBYTE
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeUBYTE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeUBYTE
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeSHORT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeSHORT
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeUSHORT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeUSHORT
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeINT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeINT
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeUINT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeUINT
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeLONG
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeLONG
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeULONG
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeULONG
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeFLOAT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeFLOAT
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeDOUBLE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeDOUBLE
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeCATEGORY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeCATEGORY
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeTEXT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeTEXT
  (JNIEnv *, jclass);

/*
 * Class:     com_globalpark_fastbit_FastbitTable
 * Method:    typeBLOB
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitTable_typeBLOB
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
