/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_globalpark_fastbit_FastbitResultRow */

#ifndef _Included_com_globalpark_fastbit_FastbitResultRow
#define _Included_com_globalpark_fastbit_FastbitResultRow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsShort_native
 * Signature: (JLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsShort_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsUShort_native
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsUShort_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsInt_native
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsInt_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsUInt_native
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsUInt_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsLong_native
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsLong_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsULong_native
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsULong_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsFloat_native
 * Signature: (JLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsFloat_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsDouble_native
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsDouble_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnAsString_native
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnAsString_1native
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsShort_native
 * Signature: (JI)S
 */
JNIEXPORT jshort JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsShort_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsUShort_native
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsUShort_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsInt_native
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsInt_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsUInt_native
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsUInt_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsLong_native
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsLong_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsULong_native
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsULong_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsFloat_native
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsFloat_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsDouble_native
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsDouble_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    getColumnNumAsString_native
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_globalpark_fastbit_FastbitResultRow_getColumnNumAsString_1native
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    asString_native
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_globalpark_fastbit_FastbitResultRow_asString_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_globalpark_fastbit_FastbitResultRow
 * Method:    dump_native
 * Signature: (JLjava/io/Writer;)V
 */
JNIEXPORT void JNICALL Java_com_globalpark_fastbit_FastbitResultRow_dump_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
